### ISSUE TITLE
Understanding the logic

### ISSUE THREAD

**Issue by hesa2020** [yetzt/boxing#8]
Hey im trying to understand the logic and how to use this properly.

Here is the code i used for testing:
```php
$boxing = new Boxing();
        $boxing->add_outer_box(100, 100, 100);

        $boxing->add_inner_box(50, 50, 50); //1/4
        $boxing->add_inner_box(50, 50, 50); //1/4

        if ($boxing->fits())
        {
            var_dump($boxing);
        }
```
        
It returns a array of outer_boxes of length 6, which confuses me.
The first 2 item in the outer_boxes array are set has "Packed" true.

Can I get a return that say of item 1,2,3 goes in box 1 and item 4,5,6 goes in box 2 for example.

**Comment by yetzt** [comment]
i've written this code a long time ago. if i remember correctly, what it does is: iterate over all the inner boxes, find for the "most compact" way to fit the current inner box into the smallest possible outer box, and then slices the match into subboxes, one of which is congruent to the current inner box and therefore marked as "packed", also the matched outer box is marked "packed". it basically just means "do not match against this any more, this space is used".

you could modify the code to give the outer boxes some id and pass it along to figure out which box an item ends up in. feel free to fork.

keep in mind, the algorithm will most likely not produce the optimal solution (which is np-hard), only "this is guaranteed to fit". 

btw, 50×50×50 is 1/8 of 100×100×100.
